name: Build 1.12.2
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: adopt
      - name: Copy wrapper jar
        run: cp gradle/wrapper/gradle-wrapper.jar testing/1.12.2-Forge-Fabric/gradle/wrapper/
      - name: Grant execute permission for gradlew
        working-directory: ./testing/1.12.2-Forge-Fabric
        run: chmod +x gradlew
      - name: Build
        working-directory: ./testing/1.12.2-Forge-Fabric
        run: ./gradlew build --stacktrace